import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Loading from "@/components/Loading";
import ReduxWrapper from "@/components/ReduxWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Smart Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    //appearance={{ baseTheme: dark }} attribute for dark theme for clerk provider
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} w-full`}>
          <ClerkLoading>
            <Loading />
          </ClerkLoading>
          <ClerkLoaded>
            <ReduxWrapper>{children}</ReduxWrapper>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
